# SPDX-FileCopyrightText: 2024 Benedikt Franke <benedikt.franke@dlr.de>
# SPDX-FileCopyrightText: 2024 Florian Heinrich <florian.heinrich@dlr.de>
#
# SPDX-License-Identifier: Apache-2.0

site_name: Federated Learning Platform

repo_name: fl-documentation
repo_url: https://github.com/DLR-KI/fl-documentation

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: deep purple
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: blue

markdown_extensions:
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde

plugins:
  - search

extra:
  social:
    - icon: dlr-logo
      link: https://www.dlr.de/en
    - icon: dlr-ki
      link: https://www.dlr.de/ki/en
    - icon: fontawesome/brands/square-github
      link: https://github.com/DLR-KI/fl-demonstrator

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - javascripts/katex.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - styles/style.css

copyright: |
  &copy; 2024
  <a href="https://www.dlr.de/en/ki/about-us/departments/algorithms-hybrid-solutions" target="_blank" rel="noopener">
    DLR KI ALG
  </a>

nav:
  - Home:
    - index.md
  - Architecture: architecture/index.md
  - Aggregation: aggregation/index.md
  - Uncertainty: uncertainty/index.md
  - Tutorial:
    - tutorial/index.md
    - "Introduction":
      - "Basic Knowledge": tutorial/introduction/basic-knowledge.md
      - "Platform Components": tutorial/introduction/components.md
      - "Client $\\leftrightarrow$ Server communication": tutorial/introduction/communication.md
    - "Create your own Client":
      - "Getting started": tutorial/your-own-client/getting-started.md
    - "MNIST Example Client":
      - "Getting Started": tutorial/fl-mnist-client/getting-started.md
      - "Setup Test Environment": tutorial/fl-mnist-client/setup.md
      - "Start the Test": tutorial/fl-mnist-client/start.md
      - "FL Client Package": tutorial/fl-mnist-client/fl-mnist-client.md
  - Frontend: frontend/index.md
